name: SurrenderPlugin
version: '${project.version}'
main: me.booplayzz.surrenderplugin.SurrenderPlugin
api-version: '1.19'
commands:
  surrender:
    usage: /<command>
  pack:
    usage: /<command>
    aliases: [texturepack]